### PR TITLE
Updated the flyer to the new version.

### PR DESCRIPTION
**Pull request by dgershman**
Added breaks and a new column.

### CODE REVIEW

**Comment by pjaudiomv** [comment]
I like having breaks however the new column makes it less mobile friendly, maybe move the break txt to description or topic

**Comment by dgershman** [comment]
> I like having breaks however the new column makes it less mobile friendly, maybe move the break txt to description or topic

agreed

**Comment by dgershman** [comment]
recovery meeting should be a statement, rather than a question.  we agreed to have one.

**Comment by dgershman** [comment]
> I like having breaks however the new column makes it less mobile friendly, maybe move the break txt to description or topic

Perhaps use italics for breaks to show that distinction.

**Review by ghost — APPROVED** [review]

**Review by pjaudiomv — APPROVED** [review]

**Pull request merged**
