### PR TITLE
added the zoom id for the day

### PR DESCRIPTION
**Pull request by dgershman**

### CODE REVIEW

**Review by pjaudiomv — COMMENTED** [review]
Can we add a hyperlink or phone number

**Comment by dgershman** [comment]
I'm worried about a link being spammed, which is why I didn't include it.

**Comment by pjaudiomv** [comment]
Gotcha maybe a link to zoom or brief description of platform being used. I'm thinking most people have used zoom who is attending but if they haven't I feel there should be more than just the zoom id

**Comment by jbraswell** [comment]
I agree with @pjaudiomv here. Something simple like “Download Zoom, and join using Zoom ID xxx-xxx-xxx” would work. Could link “Download Zoom” to zoom’s download page.

**Review by jbraswell — APPROVED** [review]

**Pull request merged**
